//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingRejser
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VikingRejserDBEntities : DbContext
    {
        public VikingRejserDBEntities()
            : base("name=VikingRejserDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kunde> Kundes { get; set; }
        public virtual DbSet<Rejsearrangement> Rejsearrangements { get; set; }
        public virtual DbSet<Rejsetilmeldinger> Rejsetilmeldingers { get; set; }
        public virtual DbSet<Tilmelding> Tilmeldings { get; set; }
        public virtual DbSet<Transportør> Transportør { get; set; }
    }
}
